### ISSUE TITLE
Is this still required?

### ISSUE THREAD

**Issue by csillag** [scharf/mocha-for-jetbrains#3]
The README file says:

> This is a fix for Jetbrains issue [WEB-10067 Run a single Mocha unit-test](https://youtrack.jetbrains.com/issue/WEB-10067)

Fortunately, the referenced issue says it's fixed in v11.
[WebStorm 11 beta is out](blog.jetbrains.com/webstorm/2015/10/webstorm-11-beta/)...

Is this workaround still needed?

**Comment by scharf** [comment]
...so it is not needed if you use a modern version of jetbrains tools
